### ISSUE TITLE
Shape up this repository and upload to maven central

### ISSUE THREAD

**Issue by flavorjones** [sparklemotion/nekohtml#3]
This is a sub-task of https://github.com/sparklemotion/nokogiri/issues/2437

- [x] change default head to `main`
- [x] tag the initial commit
- [x] compile and package a jar
- [x] verify the compiled jar works with nokogiri
- [x] package docs
- [x] cut a nokogiri release and upload to maven central
- [x] document the build process

**Comment by flavorjones** [comment]
Made some progress this weekend.

**Comment by Ynoriomi** [comment]
う

**Comment by flavorjones** [comment]
See efb9742 and package uploaded to https://repo.maven.apache.org/maven2/org/nokogiri/nekohtml/1.9.22.noko2/
